apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: presentation
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: presentation
    name: presentation
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: presentation:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: Presentation
      git:
        uri: https://github.com/RHsyseng/3scale-apm.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: ObvpiRV7CcYQs_oBMEuR
      type: GitHub
    - generic:
        secret: 0tmrgXL5uVFbJyf3UOXh
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: presentation
    name: presentation
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: presentation:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 2
    labels:
      app: presentation
    name: presentation
  spec:
    replicas: 1
    selector:
      app: presentation
      deploymentconfig: presentation
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: presentation
          deploymentconfig: presentation
      spec:
        containers:
        - env:
          - name: USER_KEY
            valueFrom:
                secretKeyRef:
                    name: 3scale-secret
                    key: user_key            
          imagePullPolicy: Always
          name: presentation
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - presentation
        from:
          kind: ImageStreamTag
          name: presentation:latest
          namespace: desktop-project
      type: ImageChange
  status:
    availableReplicas: 1
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: presentation
    name: presentation
  spec:
    host: msa.example.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: presentation
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: presentation
    name: presentation
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: presentation
      deploymentconfig: presentation
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
